server:
  port: 8080
  error:
    include-message: always

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/da
    username: dauser
    password: dapassword
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: false
    show-sql: true